@echo off
REM ****************************************************************************
REM Vivado (TM) v2026.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Mon Sep 14 17:58:09 +0900 2026
REM SW Build 6511674 on Tue Jun 16 11:02:23 MDT 2026
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0

REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -prj tb_encoder8x3_vlog.prj"
call xvlog  --incr --relax -L uvm -prj tb_encoder8x3_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
